//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piaget_CSharp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// typ.: 100k (indicateur de performances)
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("typ.: 100k (indicateur de performances)")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5678")]
        public long sTicksPerSecond {
            get {
                return ((long)(this["sTicksPerSecond"]));
            }
            set {
                this["sTicksPerSecond"] = value;
            }
        }
        
        /// <summary>
        /// PasParCmGauche=4*17.9500 (RHY)
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("PasParCmGauche=4*17.9500 (RHY)")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("96.69")]
        public float sPasParCmGaucheRH {
            get {
                return ((float)(this["sPasParCmGaucheRH"]));
            }
            set {
                this["sPasParCmGaucheRH"] = value;
            }
        }
        
        /// <summary>
        /// PasParCmDroite=4*17.9500 (RHY)
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("PasParCmDroite=4*17.9500 (RHY)")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("96.69")]
        public float sPasParCmDroiteRH {
            get {
                return ((float)(this["sPasParCmDroiteRH"]));
            }
            set {
                this["sPasParCmDroiteRH"] = value;
            }
        }
        
        /// <summary>
        /// typ.: 86.5
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("typ.: 86.5")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("48.7")]
        public float sPasParCmGaucheOP {
            get {
                return ((float)(this["sPasParCmGaucheOP"]));
            }
            set {
                this["sPasParCmGaucheOP"] = value;
            }
        }
        
        /// <summary>
        /// typ.: 86.5
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("typ.: 86.5")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("48.7")]
        public float sPasParCmDroiteOP {
            get {
                return ((float)(this["sPasParCmDroiteOP"]));
            }
            set {
                this["sPasParCmDroiteOP"] = value;
            }
        }
        
        /// <summary>
        /// typ. 13.5
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("typ. 13.5")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13.5")]
        public float sPasParDegreGaucheOP {
            get {
                return ((float)(this["sPasParDegreGaucheOP"]));
            }
            set {
                this["sPasParDegreGaucheOP"] = value;
            }
        }
        
        /// <summary>
        /// 13.5
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("13.5")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13.5")]
        public float sPasParDegreDroiteOP {
            get {
                return ((float)(this["sPasParDegreDroiteOP"]));
            }
            set {
                this["sPasParDegreDroiteOP"] = value;
            }
        }
        
        /// <summary>
        /// Dude 9.6cm
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Dude 9.6cm")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public float sDemiEcartRouesExtOP {
            get {
                return ((float)(this["sDemiEcartRouesExtOP"]));
            }
            set {
                this["sDemiEcartRouesExtOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19.5")]
        public float sDemiEcartRouesExtRH {
            get {
                return ((float)(this["sDemiEcartRouesExtRH"]));
            }
            set {
                this["sDemiEcartRouesExtRH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sModeRHYorOPYlow {
            get {
                return ((bool)(this["sModeRHYorOPYlow"]));
            }
            set {
                this["sModeRHYorOPYlow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float sPasParDegreGaucheRH {
            get {
                return ((float)(this["sPasParDegreGaucheRH"]));
            }
            set {
                this["sPasParDegreGaucheRH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float sPasParDegreDroiteRH {
            get {
                return ((float)(this["sPasParDegreDroiteRH"]));
            }
            set {
                this["sPasParDegreDroiteRH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16.4")]
        public float sPasParDegreRobotGaucheOP {
            get {
                return ((float)(this["sPasParDegreRobotGaucheOP"]));
            }
            set {
                this["sPasParDegreRobotGaucheOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float sPasParDegreRobotDroiteOP {
            get {
                return ((float)(this["sPasParDegreRobotDroiteOP"]));
            }
            set {
                this["sPasParDegreRobotDroiteOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16.4")]
        public float sPasParDegreRobotDroiteRH {
            get {
                return ((float)(this["sPasParDegreRobotDroiteRH"]));
            }
            set {
                this["sPasParDegreRobotDroiteRH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32.64")]
        public float sPasParDegreRobotGaucheRH {
            get {
                return ((float)(this["sPasParDegreRobotGaucheRH"]));
            }
            set {
                this["sPasParDegreRobotGaucheRH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float sPasParCmGaucheOP12Y {
            get {
                return ((float)(this["sPasParCmGaucheOP12Y"]));
            }
            set {
                this["sPasParCmGaucheOP12Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public float sPasParCmDroiteOP12Y {
            get {
                return ((float)(this["sPasParCmDroiteOP12Y"]));
            }
            set {
                this["sPasParCmDroiteOP12Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public float sPasParDegreRobotGaucheOP12Y {
            get {
                return ((float)(this["sPasParDegreRobotGaucheOP12Y"]));
            }
            set {
                this["sPasParDegreRobotGaucheOP12Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public float sPasParDegreRobotDroiteOP12Y {
            get {
                return ((float)(this["sPasParDegreRobotDroiteOP12Y"]));
            }
            set {
                this["sPasParDegreRobotDroiteOP12Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public float sDemiEcartRouesExtOP12Y {
            get {
                return ((float)(this["sDemiEcartRouesExtOP12Y"]));
            }
            set {
                this["sDemiEcartRouesExtOP12Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public float sPasParDegreRoueOP12Y {
            get {
                return ((float)(this["sPasParDegreRoueOP12Y"]));
            }
            set {
                this["sPasParDegreRoueOP12Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sInverseSensLineaire {
            get {
                return ((bool)(this["sInverseSensLineaire"]));
            }
            set {
                this["sInverseSensLineaire"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sInverseSensRotation {
            get {
                return ((bool)(this["sInverseSensRotation"]));
            }
            set {
                this["sInverseSensRotation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sInverseCoteRotationXCentree {
            get {
                return ((bool)(this["sInverseCoteRotationXCentree"]));
            }
            set {
                this["sInverseCoteRotationXCentree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("42.21")]
        public float sVitesseMaxGlobale {
            get {
                return ((float)(this["sVitesseMaxGlobale"]));
            }
            set {
                this["sVitesseMaxGlobale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("31")]
        public float sAccelerationMaxGlobale {
            get {
                return ((float)(this["sAccelerationMaxGlobale"]));
            }
            set {
                this["sAccelerationMaxGlobale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.49")]
        public float sReductionDAccelerationEnRotation {
            get {
                return ((float)(this["sReductionDAccelerationEnRotation"]));
            }
            set {
                this["sReductionDAccelerationEnRotation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float sFacteurDecelerationMax {
            get {
                return ((float)(this["sFacteurDecelerationMax"]));
            }
            set {
                this["sFacteurDecelerationMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public float sModeReglageNoirBlanc {
            get {
                return ((float)(this["sModeReglageNoirBlanc"]));
            }
            set {
                this["sModeReglageNoirBlanc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public float sModeReglageTeinte {
            get {
                return ((float)(this["sModeReglageTeinte"]));
            }
            set {
                this["sModeReglageTeinte"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public float sModeImage {
            get {
                return ((float)(this["sModeImage"]));
            }
            set {
                this["sModeImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string sRAHColor1de9 {
            get {
                return ((string)(this["sRAHColor1de9"]));
            }
            set {
                this["sRAHColor1de9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public float sP0Robot_AngleRobotTraj {
            get {
                return ((float)(this["sP0Robot_AngleRobotTraj"]));
            }
            set {
                this["sP0Robot_AngleRobotTraj"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float sP0Robot_AngleTrajectoire {
            get {
                return ((float)(this["sP0Robot_AngleTrajectoire"]));
            }
            set {
                this["sP0Robot_AngleTrajectoire"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float sP0Robot_ds {
            get {
                return ((float)(this["sP0Robot_ds"]));
            }
            set {
                this["sP0Robot_ds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float sP0Robot_RayonTrajectoire {
            get {
                return ((float)(this["sP0Robot_RayonTrajectoire"]));
            }
            set {
                this["sP0Robot_RayonTrajectoire"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float sP0Robot_ThetaRobotDegres {
            get {
                return ((float)(this["sP0Robot_ThetaRobotDegres"]));
            }
            set {
                this["sP0Robot_ThetaRobotDegres"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float sP0Robot_x {
            get {
                return ((float)(this["sP0Robot_x"]));
            }
            set {
                this["sP0Robot_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float sP0Robot_y {
            get {
                return ((float)(this["sP0Robot_y"]));
            }
            set {
                this["sP0Robot_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool sChoix_NCSimulation_Etat {
            get {
                return ((bool)(this["sChoix_NCSimulation_Etat"]));
            }
            set {
                this["sChoix_NCSimulation_Etat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sChoix_NCGalilM27_Etat {
            get {
                return ((bool)(this["sChoix_NCGalilM27_Etat"]));
            }
            set {
                this["sChoix_NCGalilM27_Etat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sChoix_NCGalil_Etat {
            get {
                return ((bool)(this["sChoix_NCGalil_Etat"]));
            }
            set {
                this["sChoix_NCGalil_Etat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sChoixGalilFront {
            get {
                return ((bool)(this["sChoixGalilFront"]));
            }
            set {
                this["sChoixGalilFront"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sChoixGalilBack {
            get {
                return ((bool)(this["sChoixGalilBack"]));
            }
            set {
                this["sChoixGalilBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int sPlatform {
            get {
                return ((int)(this["sPlatform"]));
            }
            set {
                this["sPlatform"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sChoix_NCShoulder_Etat {
            get {
                return ((bool)(this["sChoix_NCShoulder_Etat"]));
            }
            set {
                this["sChoix_NCShoulder_Etat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sChoix_NCHand_Etat {
            get {
                return ((bool)(this["sChoix_NCHand_Etat"]));
            }
            set {
                this["sChoix_NCHand_Etat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sChoixLaserA {
            get {
                return ((bool)(this["sChoixLaserA"]));
            }
            set {
                this["sChoixLaserA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sChoixLaserB {
            get {
                return ((bool)(this["sChoixLaserB"]));
            }
            set {
                this["sChoixLaserB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sChoixLaserC {
            get {
                return ((bool)(this["sChoixLaserC"]));
            }
            set {
                this["sChoixLaserC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sChoix_NCCamera_Etat {
            get {
                return ((bool)(this["sChoix_NCCamera_Etat"]));
            }
            set {
                this["sChoix_NCCamera_Etat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sChoix_NCBeckhoff_Etat {
            get {
                return ((bool)(this["sChoix_NCBeckhoff_Etat"]));
            }
            set {
                this["sChoix_NCBeckhoff_Etat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sModeNewLaser {
            get {
                return ((bool)(this["sModeNewLaser"]));
            }
            set {
                this["sModeNewLaser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sKinectConnection {
            get {
                return ((bool)(this["sKinectConnection"]));
            }
            set {
                this["sKinectConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int sSimulationImageNumber {
            get {
                return ((int)(this["sSimulationImageNumber"]));
            }
            set {
                this["sSimulationImageNumber"] = value;
            }
        }
    }
}
